services:
  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nsi-cli
    volumes:
      - ./src:/app
      - ./bin:/app/bin
      - ./config/nsi-cli.dev.toml:/root/.config/nsi/nsi-cli.toml
    networks:
      - nsi-net

networks:
  nsi-net:
    name: nsi_dev_network
    external: true
