services:
  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nsi-cli
    volumes:
      - ./src:/app
      - ./config:/etc/nsi
    networks:
      - nsi-net

networks:
  nsi-net:
    name: nsi_dev_network
    external: true
